# Generated by Django 5.2.10 on 2026-02-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentreceipt',
            table='paymentreceipt',
        ),
    ]
