# Generated by Django 5.2.10 on 2026-02-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webapp', '0002_alter_paymentreceipt_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('approve_saleorder', 'Can approve sale order'), ('cancel_saleorder', 'Can cancel sale order')]},
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.category'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_name', models.CharField(help_text='Django URL name (e.g. user_list, dashboard)', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Which roles can see this menu', to='auth.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webapp.menu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
