# Generated by Django 5.2.10 on 2026-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_menu_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url_name',
            field=models.CharField(blank=True, help_text='Django URL name (e.g. user_list, dashboard)', max_length=100, null=True),
        ),
    ]
