# Generated by Django 5.0.6 on 2026-02-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webapp', '0006_alter_menu_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'permissions': [('approve_paymentreceipt', 'Can approve payment receipt'), ('reject_paymentreceipt', 'Can reject payment receipt'), ('approve_request_paymentreceipt', 'Can request to approve the payment receipt'), ('cancel_request_paymentreceipt', 'Can request to cancel the payment receipt'), ('approve_cancelrequest_paymentreceipt', 'Can approve the cancel request payment receipt'), ('reject_cancelrequest_paymentreceipt', 'Can reject the cancel request payment receipt')]},
        ),
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'ordering': ['-date'], 'permissions': [('approve_saleinvoice', 'Can approve sale invoice'), ('reject_saleinvoice', 'Can reject sale invoice'), ('approve_request_saleinvoice', 'Can request to approve the sale invoice'), ('cancel_request_saleinvoice', 'Can request to cancel the sale invoice'), ('approve_cancelrequest_saleinvoice', 'Can approve the cancel request sale invoice'), ('reject_cancelrequest_saleinvoice', 'Can reject the cancel request sale invoice')]},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('approve_saleorder', 'Can approve the sale order'), ('reject_saleorder', 'Can reject the sale order'), ('approve_request_saleorder', 'Can request to approve the sale order'), ('cancel_request_saleorder', 'Can request to cancel the sale order'), ('approve_cancelrequest_saleorder', 'Can approve the cancel request sale order'), ('reject_cancelrequest_saleorder', 'Can reject the cancel request sale order')]},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.AddField(
            model_name='saleorderdetails',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancel_requested', 'Cancel Requested'), ('cancel_approved', 'Cancel Approved'), ('cancel_rejected', 'Cancel Rejected')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancel_requested', 'Cancel Requested'), ('cancel_approved', 'Cancel Approved'), ('cancel_rejected', 'Cancel Rejected')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='portal_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancel_requested', 'Cancel Requested'), ('cancel_approved', 'Cancel Approved'), ('cancel_rejected', 'Cancel Rejected')], default='draft', max_length=100),
        ),
    ]
