# Generated by Django 5.0.6 on 2026-02-22 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_paymentreceipt_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderdetails',
            name='status',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancel_requested', 'Cancel Requested'), ('cancel_approved', 'Cancel Approved'), ('cancel_rejected', 'Cancel Rejected')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.outlet'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.product'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='webapp.menu'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.customer'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.saleorder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.category'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.customer'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.employee'),
        ),
        migrations.AlterField(
            model_name='saleinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='webapp.saleinvoice'),
        ),
        migrations.AlterField(
            model_name='saleinvoiceline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.product'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.customer'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.employee'),
        ),
        migrations.AlterField(
            model_name='saleorderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='webapp.saleorder'),
        ),
        migrations.AlterField(
            model_name='saleorderdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.product'),
        ),
        migrations.AlterField(
            model_name='saleorderdetails',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
