# Generated by Django 5.2.10 on 2026-03-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_inventory_options_alter_inventory_outlet_and_more'),
        ('webapp', '0008_remove_saleorderdetails_status_saleorder_status_and_more'),
    ]

    operations = [
    ]
